DROP DATABASE IF EXISTS `taxis`;
CREATE DATABASE IF NOT EXISTS `taxis` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `taxis`;

DROP TABLE IF EXISTS `association_vehicule_conducteur`;
DROP TABLE IF EXISTS `vehicule`;
DROP TABLE IF EXISTS `conducteur`;

CREATE TABLE `conducteur` (
  `id_conducteur` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) NOT NULL,
  `prenom` varchar(50) NOT NULL,
  PRIMARY KEY (`id_conducteur`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehicule` (
  `id_vehicule` int(11) NOT NULL AUTO_INCREMENT,
  `marque` varchar(30) NOT NULL,
  `modele` varchar(50) NOT NULL,
  `couleur` varchar(20) NOT NULL,
  `immatriculation` varchar(15) NOT NULL,
  PRIMARY KEY (`id_vehicule`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `association_vehicule_conducteur` (
  `id_association` int(11) NOT NULL AUTO_INCREMENT,
  `id_conducteur` int(11) NOT NULL,
  `id_vehicule` int(11) NOT NULL,
  PRIMARY KEY (`id_association`),
  KEY `id_conducteur` (`id_conducteur`),
  KEY `id_vehicule` (`id_vehicule`),
  CONSTRAINT `association_vehicule_conducteur_ibfk_1` FOREIGN KEY (`id_conducteur`) REFERENCES `conducteur` (`id_conducteur`) ON DELETE CASCADE,
  CONSTRAINT `association_vehicule_conducteur_ibfk_2` FOREIGN KEY (`id_vehicule`) REFERENCES `vehicule` (`id_vehicule`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `conducteur` (`nom`, `prenom`) VALUES
('Martin', 'Sophie'),
('Pandre', 'Philippe'),
('Avigny', 'Julien'),
('Dupont', 'Alexandre'),
('Bernard', 'Marie'),
('Lefevre', 'Pierre'),
('Roux', 'Julie'),
('Moreau', 'Thomas'),
('Simon', 'Laura'),
('Durand', 'Nicolas'),
('Petit', 'Camille'),
('Robert', 'Lucas'),
('Richard', 'Emma'),
('Dubois', 'Hugo'),
('Garcia', 'Léa'),
('Fontaine', 'Nathan'),
('Rousseau', 'Chloé'),
('Blanc', 'Louis'),
('Guerin', 'Manon'),
('Muller', 'Théo'),
('Garnier', 'Sarah'),
('Faure', 'Maxime'),
('Lemoine', 'Inès'),
('Bonnet', 'Antoine'),
('Mercier', 'Zoé'),
('Vincent', 'Gabriel'),
('Boyer', 'Jade'),
('Girard', 'Raphaël'),
('Chevalier', 'Lola'),
('Francois', 'Tom'),
('Lambert', 'Lily'),
('Moulin', 'Arthur'),
('Leclerc', 'Alice'),
('Lopez', 'Paul'),
('Clement', 'Rose'),
('Bertrand', 'Jules'),
('Renaud', 'Eva'),
('Caron', 'Adam'),
('Fernandez', 'Anna'),
('Andre', 'Victor'),
('Gauthier', 'Mia'),
('Perrin', 'Oscar'),
('Legrand', 'Nina'),
('Colin', 'Ethan'),
('Vidal', 'Lucie'),
('Roche', 'Noah'),
('Picard', 'Clara'),
('Roy', 'Mathis'),
('Fournier', 'Giulia'),
('Giraud', 'Léon'),
('Barbier', 'Charlotte'),
('Arnaud', 'Nolan'),
('Marchand', 'Romane'),
('Dumas', 'Timéo'),
('Rey', 'Ambre'),
('Morel', 'Benjamin'),
('Henry', 'Louise'),
('Denis', 'Samuel'),
('Leroux', 'Apolline'),
('Martinez', 'Dylan');

INSERT INTO `vehicule` (`marque`, `modele`, `couleur`, `immatriculation`) VALUES
('Renault', 'Scenic', 'rouge', 'DD-456-ZZ'),
('Citroën', 'C8', 'bleu', 'AB-123-CD'),
('Mercedes', 'CLS', 'noir', 'EF-789-GH'),
('Peugeot', '308', 'gris', 'IJ-456-KL'),
('Peugeot', '2008', 'noir', 'MN-123-OP'),
('Volkswagen', 'Golf', 'blanc', 'QR-456-ST'),
('Renault', 'Clio', 'noir', 'UV-789-WX'),
('Citroën', 'C3', 'rouge', 'YZ-123-AB'),
('Mercedes', 'Classe A', 'noir', 'CD-456-EF'),
('Volkswagen', 'Passat', 'bleu', 'GH-789-IJ'),
('Toyota', 'Yaris', 'blanc', 'KL-234-MN'),
('Honda', 'Civic', 'gris', 'OP-567-QR'),
('Ford', 'Focus', 'rouge', 'ST-890-UV'),
('Audi', 'A3', 'noir', 'WX-123-YZ'),
('BMW', 'Serie 1', 'bleu', 'AB-456-CD'),
('Nissan', 'Qashqai', 'blanc', 'EF-789-GH'),
('Mazda', 'CX-5', 'gris', 'IJ-012-KL'),
('Hyundai', 'i30', 'rouge', 'MN-345-OP'),
('Kia', 'Sportage', 'noir', 'QR-678-ST'),
('Seat', 'Leon', 'bleu', 'UV-901-WX'),
('Skoda', 'Octavia', 'blanc', 'YZ-234-AB'),
('Fiat', '500', 'rouge', 'CD-567-EF'),
('Opel', 'Corsa', 'gris', 'GH-890-IJ'),
('Dacia', 'Duster', 'noir', 'KL-123-MN'),
('Volvo', 'XC60', 'bleu', 'OP-456-QR'),
('Lexus', 'CT', 'blanc', 'ST-789-UV'),
('Alfa Romeo', 'Giulietta', 'rouge', 'WX-012-YZ'),
('Mini', 'Cooper', 'noir', 'AB-345-CD'),
('Jeep', 'Renegade', 'gris', 'EF-678-GH'),
('Land Rover', 'Evoque', 'bleu', 'IJ-901-KL'),
('Porsche', 'Cayenne', 'blanc', 'MN-234-OP'),
('Tesla', 'Model 3', 'noir', 'QR-567-ST'),
('Jaguar', 'XE', 'rouge', 'UV-890-WX'),
('Suzuki', 'Swift', 'bleu', 'YZ-123-AB'),
('Mitsubishi', 'Outlander', 'gris', 'CD-456-EF'),
('Subaru', 'Forester', 'blanc', 'GH-789-IJ'),
('Chevrolet', 'Cruze', 'noir', 'KL-012-MN'),
('Dodge', 'Charger', 'rouge', 'OP-345-QR'),
('Chrysler', '300', 'bleu', 'ST-678-UV'),
('Buick', 'Encore', 'gris', 'WX-901-YZ'),
('Cadillac', 'XT5', 'blanc', 'AB-234-CD'),
('Lincoln', 'MKC', 'noir', 'EF-567-GH'),
('Acura', 'MDX', 'rouge', 'IJ-890-KL'),
('Infiniti', 'Q50', 'bleu', 'MN-123-OP'),
('Genesis', 'G70', 'gris', 'QR-456-ST'),
('Maserati', 'Ghibli', 'blanc', 'UV-789-WX'),
('Ferrari', 'Roma', 'rouge', 'YZ-012-AB'),
('Lamborghini', 'Urus', 'noir', 'CD-345-EF'),
('Bentley', 'Continental', 'bleu', 'GH-678-IJ'),
('Rolls-Royce', 'Ghost', 'blanc', 'KL-901-MN'),
('Aston Martin', 'Vantage', 'gris', 'OP-234-QR'),
('McLaren', '720S', 'rouge', 'ST-567-UV'),
('Bugatti', 'Chiron', 'noir', 'WX-890-YZ'),
('Koenigsegg', 'Agera', 'bleu', 'AB-123-CD'),
('Pagani', 'Huayra', 'blanc', 'EF-456-GH'),
('Lotus', 'Evora', 'rouge', 'IJ-789-KL'),
('Morgan', 'Plus Six', 'noir', 'MN-012-OP'),
('Caterham', 'Seven', 'gris', 'QR-345-ST'),
('Ariel', 'Atom', 'bleu', 'UV-678-WX'),
('BAC', 'Mono', 'blanc', 'YZ-901-AB');

INSERT INTO `association_vehicule_conducteur` (`id_conducteur`, `id_vehicule`) VALUES
(1, 2), 
(2, 3), 
(3, 4), 
(4, 5),
(5, 3), 
(6, 1), 
(7, 6), 
(8, 7), 
(9, 2), 
(2, 9), 
(10, 10), 
(4, 4),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(21, 21),
(22, 22),
(23, 23),
(24, 24),
(25, 25),
(26, 26),
(27, 27),
(28, 28),
(29, 29),
(30, 30),
(31, 31),
(32, 32),
(33, 33),
(34, 34),
(35, 35),
(36, 36),
(37, 37),
(38, 38),
(39, 39),
(40, 40),
(41, 41),
(42, 42),
(43, 43),
(44, 44),
(45, 45),
(46, 46),
(47, 47),
(48, 48),
(49, 49),
(50, 50),
(51, 11),
(52, 12),
(53, 13),
(54, 14),
(55, 15),
(56, 16),
(57, 17),
(58, 18),
(59, 19),
(60, 20);